from _incydr_sdk.enums import _Enum


class ActivityType(_Enum):
    DOMAIN = "DOMAIN"
    ACCOUNT_NAME = "ACCOUNT_NAME"
    URL_PATH = "URL_PATH"
    SLACK = "SLACK"
    CLOUD_SHARE = "CLOUD_SHARE"
    CLOUD_SYNC = "CLOUD_SYNC"
    EMAIL = "EMAIL"
    FILE_UPLOAD = "FILE_UPLOAD"
    GIT_PUSH = "GIT_PUSH"
    GIT_REPOSITORY_URI = "GIT_REPOSITORY_URI"
    USER_ACCOUNT_UPLOAD = "USER_ACCOUNT_UPLOAD"
    FILE_TRANSFER = "FILE_TRANSFER"


class CloudSyncApps(_Enum):
    BOX = "BOX"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    ICLOUD = "ICLOUD"
    ONE_DRIVE = "ONE_DRIVE"


class CloudShareApps(_Enum):
    BOX = "BOX"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    ONE_DRIVE = "ONE_DRIVE"


class EmailServices(_Enum):
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    GMAIL = "GMAIL"
    OFFICE_365 = "OFFICE_365"


class Name(_Enum):
    DEFAULT = "DEFAULT"
    DROPBOX = "DROPBOX"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    ICLOUD = "ICLOUD"
    ONE_DRIVE = "ONE_DRIVE"
    GMAIL = "GMAIL"
    OFFICE_365 = "OFFICE_365"
    BOX = "BOX"


class PrincipalType(_Enum):
    USER = "USER"
    API_KEY = "API_KEY"
    DEVICE = "DEVICE"
    SERVICE = "SERVICE"


class SortKeys(_Enum):
    ACTIVITY_ID = "ACTIVITY_ID"
    DESCRIPTION = "DESCRIPTION"
    TYPE = "TYPE"
    UPDATED_BY_PRINCIPAL_NAME = "UPDATED_BY_PRINCIPAL_NAME"
    UPDATE_TIME = "UPDATE_TIME"
    VALUE = "VALUE"


class BrowserDestination(_Enum):
    AIRTABLE = "AIRTABLE"
    AMAZON_WEB_SERVICES = "AMAZON_WEB_SERVICES"
    BLACKBOX = "BLACKBOX"
    BOX = "BOX"
    CHATGPT = "CHATGPT"
    CLAUDE = "CLAUDE"
    CONCUR = "CONCUR"
    CURSOR = "CURSOR"
    DROPBOX = "DROPBOX"
    GOOGLE_WORKSPACE = "GOOGLE_WORKSPACE"
    MICROSOFT_365 = "MICROSOFT_365"
    NOTTA = "NOTTA"
    OTTER = "OTTER"
    PERPLEXITY = "PERPLEXITY"
    SLACK = "SLACK"
    YOU_DOT_COM = "YOU_DOT_COM"
